### ISSUE TITLE
Image Assets are not not being loaded with the index.html

### ISSUE THREAD

**Issue by lpappas28** [wottreng/Flask-Serving-Angular#1]
When I use your method to serve my angular project with Flask I am running into a problem where the webserver starts up with the angular project but it is unable to find the assets folder in the dist with all of the needed image files.

**Comment by wottreng** [comment]
I added a route to the `flaskBackend.py` to handle this request. This should solve your issue

**Comment by lpappas28** [comment]
That worked perfect! Thank you!
